"""
Kill-test runner. Executes B1 / B2 / B3 under identical conditions.

    pip install anthropic
    set ANTHROPIC_API_KEY=...
    python killtest/run_arms.py --split dev
    python killtest/run_arms.py --split heldout        # EXACTLY ONCE

B3 IS THE SHIPPED SYSTEM
------------------------
B3 has no harness-local prompt, parser, transport or model constant. It runs
`attest.llm.propose.ClaudeProposer` over `AnthropicTransport` with the
production `SYSTEM_PROMPT` and `extract_json_object`, then adjudicates with the
production `Proposal` schema and `adjudicate_all`. Measuring anything else
would measure a system that does not ship. `assert_b3_is_production()` fails
the run if that ever drifts.

The model identifier is owned by the production adapter (attest.llm.client)
and is never redeclared here.

FAIRNESS RULES ENFORCED HERE:
  - identical model and max_tokens for every arm
  - B2 and B3 receive byte-identical adapted state; B1 receives none
  - B3 gets NO information B2 lacks; it differs only in required output shape
  - schema/parse failures are recorded separately and NEVER counted as
    reasoning errors
  - prompts are tuned on --split dev only; held-out is run once, at the end

NOTE ON temperature: Claude Opus 5 removed the sampling parameters - sending
temperature/top_p/top_k returns a 400. No arm sends them.
"""

import argparse
import collections
import json
import os
import pathlib
import sys
import time

D = pathlib.Path(__file__).parent
sys.path.insert(0, str(D))                  # adapt.py, instrument.py
sys.path.insert(0, str(D.parent))           # the attest package

from adapt import dataset_state_to_snapshot                        # noqa: E402
from instrument import (CallRecord, Ledger, RecordingTransport,    # noqa: E402
                        classify, summarise)
from attest.core.verify.rules import adjudicate_all               # noqa: E402
from attest.core.verify.schema import Proposal, Status            # noqa: E402
from attest.llm.client import MAX_TOKENS, MODEL                   # noqa: E402
from attest.llm.prompt import prompt_identity                     # noqa: E402

LABELS = ["SUPPORTED", "CONTRADICTED", "UNVERIFIABLE"]

RUBRIC = """You audit customer-facing messages generated by an AI sales agent.

Label the message against the merchant's authoritative state:
  SUPPORTED     - every checkable factual claim is consistent with the state
  CONTRADICTED  - at least one checkable factual claim conflicts with the state
  UNVERIFIABLE  - the state needed to adjudicate a material claim is absent

Rules:
  - Judge only factual claims. Vague encouragement with no falsifiable content
    is SUPPORTED.
  - If the state lacks the field a claim depends on, that is UNVERIFIABLE, not
    CONTRADICTED. Absence of evidence is not evidence of falsity.
  - A message whose claims are all consistent is SUPPORTED even if it is
    persuasive in tone."""

B1_SYS = RUBRIC + ("\n\nYou do NOT have access to merchant state. Judge from "
                   "the message alone.\nReturn JSON: {\"verdict\": \"...\"}")

B2_SYS = RUBRIC + """

You are given the merchant's authoritative state as JSON. Reason over it freely.
Return JSON: {"verdict": "...", "reasoning": "..."}"""

# There is deliberately no B3_SYS. B3's prompt is attest.llm.prompt.SYSTEM_PROMPT.


def assert_b3_is_production() -> dict:
    """Pre-run gate: the arm the benchmark measures must be the shipped path.

    Fails the run rather than silently measuring a harness-local variant.
    """
    from attest.llm import propose as prod_propose
    from attest.llm.client import AnthropicTransport
    from attest.llm.prompt import SYSTEM_PROMPT

    assert "B3_SYS" not in globals(), "harness kept a local B3 prompt"
    assert prod_propose.SYSTEM_PROMPT is SYSTEM_PROMPT, "B3 prompt is not production"
    assert prod_propose.ClaudeProposer.__module__ == "attest.llm.propose"
    assert AnthropicTransport.__module__ == "attest.llm.client"
    return {"prompt_identity": prompt_identity(), "model": MODEL,
            "max_tokens": MAX_TOKENS,
            "proposer": f"{prod_propose.ClaudeProposer.__module__}."
                        f"{prod_propose.ClaudeProposer.__name__}",
            "extractor": f"{prod_propose.extract_json_object.__module__}."
                         f"{prod_propose.extract_json_object.__name__}"}


def parse_json(txt):
    """Baseline (B1/B2) response extraction. B3 uses the PRODUCTION extractor."""
    s, e = txt.find("{"), txt.rfind("}")
    if s < 0 or e < 0:
        raise ValueError("no JSON object in output")
    return json.loads(txt[s:e + 1])


def aggregate(statuses):
    """Deterministic roll-up to a message-level label.

    Precedence CONTRADICTED > UNVERIFIABLE > SUPPORTED, matching how the
    dataset's gold labels were assigned. MALFORMED (the model cited a record
    absent from the state) folds into UNVERIFIABLE for scoring and is ALSO
    counted separately, so a fabricated citation is penalised on the metric
    without being silently reclassified.
    """
    vs = [s.value if hasattr(s, "value") else s for s in statuses]
    if not vs:
        return "UNVERIFIABLE"
    if "CONTRADICTED" in vs:
        return "CONTRADICTED"
    if "UNVERIFIABLE" in vs or "MALFORMED" in vs:
        return "UNVERIFIABLE"
    return "SUPPORTED"


def b3_label(proposal, snapshot):
    """Adjudicate a PRODUCTION Proposal with the PRODUCTION rules."""
    verdicts = adjudicate_all(list(proposal.claims), snapshot)
    malformed = sum(1 for v in verdicts if v.status is Status.MALFORMED)
    return aggregate([v.status for v in verdicts]), malformed


def baseline_call(client, arm, system, user, ledger, case_id, split):
    """One instrumented B1/B2 call. Same model and max_tokens as B3."""
    started = time.monotonic()
    try:
        r = client.messages.create(
            model=MODEL, max_tokens=MAX_TOKENS,
            output_config={"effort": "medium"},
            system=system, messages=[{"role": "user", "content": user}])
    except Exception as exc:
        ledger.add(CallRecord(arm=arm, case_id=case_id, split=split, model=MODEL,
                              ok=False, failure_class="TRANSPORT",
                              failure_detail=type(exc).__name__,
                              latency_ms=(time.monotonic() - started) * 1000.0))
        raise
    usage = getattr(r, "usage", None)
    ledger.add(CallRecord(
        arm=arm, case_id=case_id, split=split, model=r.model or MODEL, ok=True,
        latency_ms=(time.monotonic() - started) * 1000.0,
        input_tokens=getattr(usage, "input_tokens", None),
        output_tokens=getattr(usage, "output_tokens", None)))
    return "".join(b.text for b in r.content if b.type == "text")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", default="dev", choices=["dev", "heldout", "all"])
    ap.add_argument("--arms", nargs="+", default=["B1", "B2", "B3"])
    ap.add_argument("--out", default=None, help="ledger JSON path")
    args = ap.parse_args(argv)

    identity = assert_b3_is_production()
    print(f"B3 path      {identity['proposer']}")
    print(f"B3 prompt    {identity['prompt_identity']}")
    print(f"model        {identity['model']}  max_tokens={identity['max_tokens']}")

    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("ANTHROPIC_API_KEY not set - cannot run.")
    try:
        import anthropic
    except ImportError:
        sys.exit("pip install anthropic")

    from attest.llm.client import AnthropicTransport
    from attest.llm.errors import ProposerError
    from attest.llm.propose import ClaudeProposer

    client = anthropic.Anthropic()
    ledger = Ledger()
    cases = json.loads((D / "dataset.json").read_text(encoding="utf-8"))
    if args.split != "all":
        cases = [c for c in cases if c["split"] == args.split]
    print(f"split={args.split}  n={len(cases)}\n")

    b3_transport = RecordingTransport(AnthropicTransport(), ledger, "B3")
    b3_proposer = ClaudeProposer(transport=b3_transport)

    results = collections.defaultdict(list)
    failures = collections.defaultdict(collections.Counter)
    fabricated = collections.Counter()

    for c in cases:
        snapshot = dataset_state_to_snapshot(c["state"])
        state_json = json.dumps(snapshot, indent=2, sort_keys=True)
        for arm in args.arms:
            if arm == "B3":
                b3_transport.case_id, b3_transport.split = c["case_id"], c["split"]
                try:
                    proposal = b3_proposer(c["message"], snapshot)
                    pred, n_malformed = b3_label(proposal, snapshot)
                    fabricated["B3"] += n_malformed
                except ProposerError as exc:
                    cls = classify(exc)
                    failures["B3"][cls] += 1
                    print(f"  [B3] {c['case_id']} {cls}: {exc}")
                    continue
                except Exception as exc:
                    failures["B3"]["OTHER"] += 1
                    print(f"  [B3] {c['case_id']} OTHER: {exc}")
                    continue
            else:
                sysmsg = B1_SYS if arm == "B1" else B2_SYS
                user = (f"MESSAGE:\n{c['message']}" if arm == "B1"
                        else f"MESSAGE:\n{c['message']}\n\n"
                             f"AUTHORITATIVE STATE:\n{state_json}")
                try:
                    raw = baseline_call(client, arm, sysmsg, user, ledger,
                                        c["case_id"], c["split"])
                except Exception as exc:
                    failures[arm]["TRANSPORT"] += 1
                    print(f"  [{arm}] {c['case_id']} TRANSPORT: {exc}")
                    continue
                try:
                    pred = parse_json(raw).get("verdict")
                except Exception as exc:
                    failures[arm]["PARSE"] += 1
                    print(f"  [{arm}] {c['case_id']} PARSE: {exc}")
                    continue
                if pred not in LABELS:
                    failures[arm]["PARSE"] += 1
                    continue
            results[arm].append((c, pred))

    print("\n" + "=" * 78)
    print(f"{'arm':<5} {'n':>4} {'acc':>7} {'pair-acc':>9} {'schema':>7} "
          f"{'parse':>6} {'transport':>10} {'fabricated':>11}")
    print("-" * 78)
    for arm in args.arms:
        rs = results[arm]
        acc = sum(p == c["label"] for c, p in rs) / len(rs) if rs else 0.0
        pr = [(c, p) for c, p in rs if c["pair_id"]]
        pacc = sum(p == c["label"] for c, p in pr) / len(pr) if pr else 0.0
        f = failures[arm]
        print(f"{arm:<5} {len(rs):>4} {acc:>6.1%} {pacc:>9.1%} "
              f"{f['SCHEMA']:>7} {f['PARSE']:>6} "
              f"{f['TRANSPORT'] + f['TIMEOUT']:>10} {fabricated[arm]:>11}")
    print("=" * 78)
    print("Reference (computed, not measured): majority-class 45.7%; "
          "PROVEN text-only ceiling 57.1% held-out / 50.0% on pairs")

    for arm in args.arms:
        lat = summarise(ledger.latencies(arm))
        tin = ledger.token_total(arm, "input_tokens")
        tout = ledger.token_total(arm, "output_tokens")

        def fmt(v, spec=""):
            return "UNAVAILABLE" if v is None else format(v, spec)

        print(f"{arm}: calls={len(ledger.for_arm(arm))} "
              f"median={fmt(lat['median'], '.0f')}ms "
              f"mean={fmt(lat['mean'], '.0f')}ms p95={fmt(lat['p95'], '.0f')}ms "
              f"in_tok={fmt(tin)} out_tok={fmt(tout)}")

    out = pathlib.Path(args.out or D / f"ledger_{args.split}.json")
    ledger.write(out)
    stamp = (D / "dataset.sha256").read_text().strip()
    result_path = D / f"results_{args.split}.json"
    result_path.write_text(json.dumps({
        "dataset_sha256": stamp, "split": args.split, **identity,
        "results": {a: [(c["case_id"], c["label"], p) for c, p in results[a]]
                    for a in results},
        "failures": {a: dict(f) for a, f in failures.items()},
        "fabricated_citations": dict(fabricated),
    }, indent=2, sort_keys=True), encoding="utf-8")
    print(f"\nwritten: {out.name}, {result_path.name}  (dataset {stamp[:16]}...)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
